import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { ClerkProvider } from "@clerk/nextjs"
import { Toaster } from "@/components/ui/toaster"

const geistSans = Geist({
	subsets: ["latin"],
	display: "swap", // Ensures fonts are swapped without blocking render
	variable: "--font-geist-sans",
})

const geistMono = Geist_Mono({
	subsets: ["latin"],
	display: "swap", // Ensures fonts are swapped without blocking render
	variable: "--font-geist-mono",
})

export const metadata = {
	title: "Interview Pro",
	description: "Generated by create next app",
}

export default function RootLayout({ children }) {
	return (
		<>
			<ClerkProvider>
				<html lang="en">
					<body
						className={`${geistSans.variable} ${geistMono.variable} antialiased`}
					>
						<Toaster />
						{children}
					</body>
				</html>
			</ClerkProvider>
		</>
	)
}
